name: Build shadPS4 Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        submodules: 'false'
        fetch-depth: 1

    - name: Sincronizar e Atualizar Submódulos
      run: |
        git submodule sync
        # Removemos o cryptoppwin do config para o git não tentar baixar o que não existe
        git config --global url."https://github.com/".insteadOf git@github.com:
        git submodule update --init --recursive --depth 1 || echo "Ignorando falhas em submódulos"

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # Removemos a linha 'cache: gradle' para evitar o erro de arquivo não encontrado

    - name: Instalar NDK e CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Build com Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: shadPS4-debug-apk
        path: app/build/outputs/apk/debug/*.apk
