name: Build shadPS4 Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        submodules: 'false' # Desativa o modo automático que trava no erro

    - name: Sincronizar e Atualizar Submódulos
      run: |
        git submodule sync
        # O "|| true" permite que o workflow continue mesmo se o cryptoppwin falhar
        git submodule update --init --recursive --depth 1 || true

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Instalar NDK e CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Build com Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: shadPS4-debug-apk
        path: app/build/outputs/apk/debug/*.apk
